const productsList = [
    {
      imgSrc: "./res/img/product01.png",
      category: "Laptops",
      name: "Laptop HP",
      oldPrice: 200,
      newPrice: 199,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product02.png",
      category: "Headphones",
      name: "Headset 1",
      oldPrice: 27,
      newPrice: "",
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product03.png",
      category: "Laptops",
      name: "Laptop Dell",
      oldPrice: 201,
      newPrice: 200,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product04.png",
      category: "Tablets",
      name: "Tablet",
      oldPrice: 33,
      newPrice: 32.5,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product05.png",
      category: "Headphones",
      name: "Headset 2",
      oldPrice: 20,
      newPrice: 18,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product06.png",
      category: "Laptops",
      name: "Lenovo",
      oldPrice: 207,
      newPrice: 205,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product07.png",
      category: "Mobiles",
      name: "Product 1",
      oldPrice: 130,
      newPrice: 129,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product08.png",
      category: "Laptops",
      name: "Product 1",
      oldPrice: "",
      newPrice: 150,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
    {
      imgSrc: "./res/img/product09.png",
      category: "Cameras",
      name: "Canon",
      oldPrice: 180,
      newPrice: 170,
      rating: "",
      isNew: false,
      wishlisted: false,
    },
  ];

  let userProduct = ''